@base-url = http://localhost:8080/api/recipe
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJyZWNpcGVzLUFQSSIsInN1YiI6InBtIiwiYXBwVXNlcklkIjozLCJhdXRob3JpdGllcyI6WyJVU0VSIiwiQURNSU4iXSwiZXhwIjoxNjgwNjY0MjUxfQ.g4ru499orM4NXE6g4lXr3ptaY4d37NcE638n_vZnlkk
###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "appuser",
    "password": "user"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "pm",
    "password": "paul"
}

###
// findAll
GET {{base-url}} HTTP/1.1

###
//find good id

GET {{base-url}}/3 HTTP/1.1
Authorization: Bearer {{jwt}}
###

//find bad id

GET {{base-url}}/99 HTTP/1.1
Authorization: Bearer {{jwt}}
###

//Good Post
POST {{base-url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "title": "Test",
  "instructions": "Test instructions",
  "recipeDescription": "Test",
  "cookTime": 0,
  "prepTime": 10,
  "calories": 115,
  "servings": 4,
  "imageUrl": "https://loveandgoodstuff.com/wp-content/uploads/2019/07/italian-tomato-salad-6.jpg"
}

###
//Update Good
PUT {{base-url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "recipeId": 4,
  "title": "Test",
  "instructions": "Test instructions",
  "recipeDescription": "TestChange",
  "cookTime": 0,
  "prepTime": 10,
  "calories": 115,
  "servings": 4,
  "imageUrl": "https://loveandgoodstuff.com/wp-content/uploads/2019/07/italian-tomato-salad-6.jpg",
  "tags": [],
  "foods": []
}
###
//Update Bad
PUT {{base-url}}/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "recipeId": 4,
  "title": "Test",
  "instructions": "Test instructions",
  "recipeDescription": "",
  "cookTime": 0,
  "prepTime": 10,
  "calories": 115,
  "servings": 4,
  "imageUrl": "https://loveandgoodstuff.com/wp-content/uploads/2019/07/italian-tomato-salad-6.jpg",
  "tags": [],
  "foods": []
}
###
DELETE {{base-url}}/4 HTTP/1.1
Authorization: Bearer {{jwt}}